version: '1'
services:
  postgres:
    image: postgres
    build: .
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: wh_user
        POSTGRES_DB: warehouse_db
        POSTGRES_PASSWORD: 54321
      container_name: warehouse_db

  wh:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    container_name: warehouse_service
